/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BadEventQueueIdError struct for BadEventQueueIdError
type BadEventQueueIdError struct {
	Result map[string]interface{} `json:"result"`
	Msg map[string]interface{} `json:"msg"`
	Code map[string]interface{} `json:"code,omitempty"`
	// The string that identifies the invalid event queue. 
	QueueId string `json:"queue_id,omitempty"`
}
