/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// NonExistingStreamError struct for NonExistingStreamError
type NonExistingStreamError struct {
	Result map[string]interface{} `json:"result"`
	Msg map[string]interface{} `json:"msg"`
	Code map[string]interface{} `json:"code,omitempty"`
	// The name of the stream that could not be found. 
	Stream string `json:"stream,omitempty"`
}
