/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InvalidApiKeyError struct for InvalidApiKeyError
type InvalidApiKeyError struct {
	Result map[string]interface{} `json:"result"`
	Msg map[string]interface{} `json:"msg"`
}
