/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ApiKeyResponse struct for ApiKeyResponse
type ApiKeyResponse struct {
	Result string `json:"result"`
	Msg string `json:"msg"`
}
