/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// JsonResponse struct for JsonResponse
type JsonResponse struct {
	Result string `json:"result,omitempty"`
}
