/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MissingArgumentError struct for MissingArgumentError
type MissingArgumentError struct {
	Result string `json:"result"`
	Msg string `json:"msg"`
	// A string that identifies the error. 
	Code string `json:"code,omitempty"`
	// It contains the information about the missing parameter. 
	VarName string `json:"var_name,omitempty"`
}
