/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Messages struct for Messages
type Messages struct {
	AvatarUrl map[string]interface{} `json:"avatar_url,omitempty"`
	Client map[string]interface{} `json:"client,omitempty"`
	Content map[string]interface{} `json:"content,omitempty"`
	ContentType map[string]interface{} `json:"content_type,omitempty"`
	DisplayRecipient map[string]interface{} `json:"display_recipient,omitempty"`
	Id map[string]interface{} `json:"id,omitempty"`
	IsMeMessage map[string]interface{} `json:"is_me_message,omitempty"`
	Reactions map[string]interface{} `json:"reactions,omitempty"`
	RecipientId map[string]interface{} `json:"recipient_id,omitempty"`
	SenderEmail map[string]interface{} `json:"sender_email,omitempty"`
	SenderFullName map[string]interface{} `json:"sender_full_name,omitempty"`
	SenderId map[string]interface{} `json:"sender_id,omitempty"`
	SenderRealmStr map[string]interface{} `json:"sender_realm_str,omitempty"`
	StreamId map[string]interface{} `json:"stream_id,omitempty"`
	Subject map[string]interface{} `json:"subject,omitempty"`
	TopicLinks map[string]interface{} `json:"topic_links,omitempty"`
	Submessages map[string]interface{} `json:"submessages,omitempty"`
	Timestamp map[string]interface{} `json:"timestamp,omitempty"`
	Type map[string]interface{} `json:"type,omitempty"`
}
