/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Messages struct for Messages
type Messages struct {
	// The URL of the user's avatar.  Can be null only if client_gravatar was passed, which means that the user has not uploaded an avatar in Zulip, and the client should compute the gravatar URL by hashing the user's email address itself for this user. 
	AvatarUrl *string `json:"avatar_url,omitempty"`
	// A Zulip \"client\" string, describing what Zulip client sent the message. 
	Client string `json:"client,omitempty"`
	// The content/body of the message. 
	Content string `json:"content,omitempty"`
	// The content/body of the message rendered in HTML. 
	RenderedContent string `json:"rendered_content,omitempty"`
	// The HTTP `content_type` for the message content.  This will be `text/html` or `text/x-markdown`, depending on whether `apply_markdown` was set. 
	ContentType string `json:"content_type,omitempty"`
	// Data on the recipient of the message; either the name of a stream or a dictionary containing basic data on the users who received the message. 
	DisplayRecipient OneOfstringarray `json:"display_recipient,omitempty"`
	// The user's [message flags][message-flags] for the message. 
	Flags []string `json:"flags,omitempty"`
	// The unique message ID.  Messages should always be displayed sorted by ID. 
	Id int32 `json:"id,omitempty"`
	// Whether the message is a [/me status message][status-messages] 
	IsMeMessage bool `json:"is_me_message,omitempty"`
	// Data on any reactions to the message. 
	Reactions []MessagesReactions `json:"reactions,omitempty"`
	// A unique ID for the set of users receiving the message (either a stream or group of users).  Useful primarily for hashing. 
	RecipientId int32 `json:"recipient_id,omitempty"`
	// The Zulip display email address of the message's sender. 
	SenderEmail string `json:"sender_email,omitempty"`
	// The full name of the message's sender. 
	SenderFullName string `json:"sender_full_name,omitempty"`
	// The user ID of the message's sender. 
	SenderId int32 `json:"sender_id,omitempty"`
	// A string identifier for the realm the sender is in.  Unique only within the context of a given Zulip server.  E.g. on `example.zulip.com`, this will be `example`. 
	SenderRealmStr string `json:"sender_realm_str,omitempty"`
	// Reserved for future use. 
	SenderShortName string `json:"sender_short_name,omitempty"`
	// Only present for stream messages; the ID of the stream. 
	StreamId int32 `json:"stream_id,omitempty"`
	// The `topic` of the message (only present for stream messages).  The field name is a legacy holdover from when topics were called \"subjects\" and will eventually change. 
	Subject string `json:"subject,omitempty"`
	// Data on any links to be included in the `topic` line (these are generated by [custom linkification filters][linkification-filters] that match content in the message's topic.)  **Changes**: New in Zulip 3.0 (feature level 1). Previously, this field was called `subject_links`; clients are recommended to rename `subject_links` to `topic_links` if present for compatibility with older Zulip servers. 
	TopicLinks []string `json:"topic_links,omitempty"`
	// Data used for certain experimental Zulip integrations. 
	Submessages []string `json:"submessages,omitempty"`
	// The UNIX timestamp for when the message was sent, in UTC seconds. 
	Timestamp int32 `json:"timestamp,omitempty"`
	// The UNIX timestamp for when the message was last edited, in UTC seconds. 
	LastEditTimestamp int32 `json:"last_edit_timestamp,omitempty"`
	// The type of the message: `stream` or `private`. 
	Type string `json:"type,omitempty"`
	// Only present if keyword search was included among the narrow parameters. HTML content of a queried message that matches the narrow, with `<span class=\"highlight\">` elements wrapping the matches for the search keywords. 
	MatchContent string `json:"match_content,omitempty"`
	// Only present if keyword search was included among the narrow parameters. HTML-escaped topic of a queried message that matches the narrow, with `<span class=\"highlight\">` elements wrapping the matches for the search keywords. 
	MatchSubject string `json:"match_subject,omitempty"`
}
