/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// User struct for User
type User struct {
	Email map[string]interface{} `json:"email,omitempty"`
	IsBot map[string]interface{} `json:"is_bot,omitempty"`
	AvatarUrl map[string]interface{} `json:"avatar_url,omitempty"`
	AvatarVersion map[string]interface{} `json:"avatar_version,omitempty"`
	FullName map[string]interface{} `json:"full_name,omitempty"`
	IsAdmin map[string]interface{} `json:"is_admin,omitempty"`
	IsOwner map[string]interface{} `json:"is_owner,omitempty"`
	BotType map[string]interface{} `json:"bot_type,omitempty"`
	UserId map[string]interface{} `json:"user_id,omitempty"`
	BotOwnerId map[string]interface{} `json:"bot_owner_id,omitempty"`
	IsActive map[string]interface{} `json:"is_active,omitempty"`
	IsGuest map[string]interface{} `json:"is_guest,omitempty"`
	Timezone map[string]interface{} `json:"timezone,omitempty"`
	DateJoined map[string]interface{} `json:"date_joined,omitempty"`
	DeliveryEmail map[string]interface{} `json:"delivery_email,omitempty"`
	ProfileData map[string]interface{} `json:"profile_data,omitempty"`
}
