/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MissingArgumentError struct for MissingArgumentError
type MissingArgumentError struct {
	Result map[string]interface{} `json:"result"`
	Msg map[string]interface{} `json:"msg"`
	Code map[string]interface{} `json:"code,omitempty"`
	// It contains the information about the missing parameter. 
	VarName string `json:"var_name,omitempty"`
}
