/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ApiKeyResponse struct for ApiKeyResponse
type ApiKeyResponse struct {
	Result map[string]interface{} `json:"result"`
	Msg map[string]interface{} `json:"msg"`
	// The API key that can be used to authenticate as the requested user. 
	ApiKey string `json:"api_key"`
	// The email address of the user who owns the API key 
	Email string `json:"email"`
}
